### ISSUE TITLE
Non-deterministic `RuntimeWarning`

### ISSUE THREAD

**Issue by PatrickAuld** [src-d/hercules#102]
I have seen the below error multiple times on different repos. Running the exact command again does not reproduce the issues reliably. I'm only seen this running against git repos on the local disk; it has never occured while running against an `https://` or `git://` URL (but I have run far fewer of those). I'm using the Docker containers to run both hercules and labours.py. Sorry for the slight fuzzy ticket but it only happens every ~10 runs so its difficult to dig into. I'm running on Mac using Docker for Mac.

Here is the command I'm running: `docker run -v $(pwd):/code --rm srcd/hercules hercules --burndown --burndown-people --pb /code/git-repo | docker run --rm -i -v /tmp:/io srcd/hercules labours.py -f pb -m all -o /io/image.png`

And the error that sometimes happens but not always.
```
/usr/local/bin/labours.py:366: RuntimeWarning: invalid value encountered in double_scalars
  / (lifetimes.sum() * matrix.shape[1]))
```

**Comment by vmarkovtsev** [comment]
Thanks for reporting @PatrickAuld 

This error seems to happen while calculating the lifetime index and is not directly used in the plotting. The bigger the index, the more stable the repository. So it can be safely ignored.

The cause is the division by zero. You extract `--burndown-people` and that lifetime index is calculated per developer. There seem to be a developer without any tracked line information hence `lifetimes.sum()` is equal to 0. I obviously need to add the check for zeros.

Yet this does not explain why sometimes the error appears and sometimes it doesn't. It it possible to send me an anonymized YAML file to reproduce?

**Comment by PatrickAuld** [comment]
I'll run it a few more times this weekend and see if I can reproduce.

**Comment by vmarkovtsev** [comment]
Considering as resolved. Please reopen if the problem returns.
