### ISSUE TITLE
question: how to use samples

### ISSUE THREAD

**Issue by bobheadxi** [src-d/hercules#235]
Here's a `GlobalHistory` from a `burndown` I generated:

```
[
  [1086,  0, 0,0, 0,0],
  [1022,389, 0,0, 0,0],
  [1022,389,29,0, 0,0],
  [1022,389,29,0, 0,0],
  [1011,365,29,0,58,0],
  [1011,365,29,0,56,2]],
]
```

Just from reading the documentation regarding [granularity and sampling configuration](https://sourcegraph.com/github.com/src-d/hercules/-/blob/leaves/burndown.go#L40) and the [output](https://sourcegraph.com/github.com/src-d/hercules/-/blob/leaves/burndown.go#L113) I can't seem to work out how exactly to leverage this data, for example to generate a [graph like the one in the README](https://github.com/src-d/hercules/blob/master/doc/linux.png). I'm guessing the bands are periods of time, but what about the samples? Should I average the samples for each band, e.g.

```
band[0] = (1086 + 1022 + 1022 + 1022 + 1011 + 1011) / 6
```

Any pointers would be appreciated - links to relevant parts of `labours.py` or similar would be super helpful too, thanks!

**Comment by vmarkovtsev** [comment]
So the rows of the matrix are samples, and the columns are bands. A "band" is something that you measure, and a "sample" is a measurement event. We measure how many lines which appeared in a certain time interval are still not overwritten through time. Let's say that our band size - granularity - is 30 days, and our sampling frequency is 1 day. This means that we record **every day** how many lines that were written between September 1st and September 30th are still alive. The matrix size will be <many many rows, for each day> x <a few columns, for each 30-day interval>.

This is why your matrix is [lower triangular](https://en.wikipedia.org/wiki/Triangular_matrix#Description): granularity equals to sampling. For example, only the first time interval makes sense for the first row, the rest are zeros because they don't exist yet, they will be written in the future. There are two sensible columns for the second row, and so on.

You should also see that the values along each column monotonically decrease. The explanation is left for readers :smile: 

Relevant places in `labours.py`: https://github.com/src-d/hercules/blob/master/labours.py#L581 and https://github.com/src-d/hercules/blob/master/labours.py#L794 I am doing an optional resampling there, which is quite tricky for this type of matrix: bands and samples are in the same timeline.

**Comment by bobheadxi** [comment]
thanks a lot @vmarkovtsev for the detailed response! I'll keep experimenting 😄

**Comment by vmarkovtsev** [comment]
Shall we close this @bobheadxi?

**Comment by bobheadxi** [comment]
Yep, I'll close this for now thanks!
