### ISSUE TITLE
No data has been read 

### ISSUE THREAD

**Issue by abirhajji** [src-d/hercules#248]
This is what I get after running 
`hercules --couples <repo> | python labours.py`

`Total 666412 (delta 518548), reused 652325 (delta 506610)                                                                                                                                        No data has been read - has Hercules crashed?`

**Comment by vmarkovtsev** [comment]
Try

```
hercules --couples <repo> >result.json
```

and see if there is any output. According to the log, no analysis happened at all.

**Comment by abirhajji** [comment]
Hi,
I tired 
`hercules --couples <repo> >result.json`

the result.json is empty and this what it gives
`

2 / 21049 [>------------------------------------------------] 32m59s [331616e] Killed
--


`

**Comment by vmarkovtsev** [comment]
You can check `dmesg`: most likely you get an OOM. Try to monitor the memory consumption with `/usr/bin/time -v hercules --couples <repo>` (**not** `time -v ...`).
In case you clone the repo while doing the analysis, you need to clone it on disk and read from disk instead of cloning in Hercules: it puts all the Git packfiles in memory.

**Comment by vmarkovtsev** [comment]
Assuming this as resolved. Please ping here if there is something left.
