### ISSUE TITLE
Feature Request: Ability to specify a timerange for analysis

### ISSUE THREAD

**Issue by DrEsteban** [src-d/hercules#287]
For developers that have annual/semi-annual reviews, they may want the ability to show burndowns for a specific time range.  That is, show me my stats for the last "review period".  Rather than calculating the stats for the entire lifetime of the project.

**Comment by vmarkovtsev** [comment]
@DrEsteban there are `--start-date` and `--end-date`, will they help in this case?

**Comment by DrEsteban** [comment]
@vmarkovtsev Oh!  I didn't realize those were existing options.  I can't find them anywhere in the helptext `hercules --help`.  My version is:
```
Version: 10
Git:     3b04d23caccc40d1ca8ffcd7f62669b3ff36a1ed
```

**Comment by vmarkovtsev** [comment]
That's the plotting layer, `labours`

**Comment by danielcorreia96** [comment]
In case @DrEsteban wants to reduce the analysis overhead of hercules (instead of labours), I ran into a similar problem recently where I wanted to run couples analyses for specific date intervals.

I solved it using `--since` + `--until` on `git rev-list` and followed the suggestion in the README for passing a file list of commits.

File Couples Example (assuming current directory is the target repository): 
`git rev-list --since="2018-03-01" --until="2019-03-01" HEAD | tac | hercules --commits - --couples . | tee output.yaml`

Ref: https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---sinceltdategt

**Comment by vmarkovtsev** [comment]
I guess that the issue has been resolved. Please ping here if there is still something unclear.
